---
- name: Instalar y configurar Git en todos los nodos Jasmin
  hosts: all
  become: yes
  tasks:

    - name: Instalar Git
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Configurar nombre y correo global
      shell: |
        git config --global user.name "Victor"
        git config --global user.email "victor@vozdigital.net"
      args:
        executable: /bin/bash

    - name: Verificar instalación
      shell: "git --version"
      register: git_version
      changed_when: false

    - debug:
        msg:
          - "Git instalado en {{ inventory_hostname }}"
          - "Versión: {{ git_version.stdout }}"
